# 조건 확인 함수
## 조건 확인 함수
* 이 문서에서는 이와 같이 특정 값의 상태를 확인하거나, 혹은 의도하지 않는 상태에서 프로그램이 계속 실행되는 것을 방지할 때 사용하는 함수들을 설명합니다.
## 특정 값의 일치 여부 확인: check, require
* 함수 혹은 생성자의 인자로 전달받은 값을 사용하기 전에, 그 값의 유효성을 검사해야 하는 경우가 있습니다. 잘못된 값이 전달되었을 경우 아무 작업도 수행하지 않고 단순히 에러 메시지를 로그로 출력하기만 해도 됩니다.
* 하지만 버그를 방지하기 위해 명시적으로 에러 발생 사실을 할리고 프로그램을 종료해야 하는 경우도 있습니다.
* 이때, check() 함수 및 require() 함수를 사용하면 이러한 작업을 쉽게 처리할 수 있습니다.
* check() 함수와 require() 함수를 사용하면 이러한 작업을 쉽게 처리할 수 있습니다. 
* check() 함수와 require() 함수 모두 인자로 받은 표현식이 참이 아닌 경우 예외를 발생시캅나더. 
* check() 함수는 IllegalStateException을, require() 함수는 IllegalArgumentException을 발생시킵니다.
* check() 함수와 require() 함수는 단순히 값을 확인만 하는 형태의 함수와, 조건이 일치하지 않을 경우 수행할 작업을 함께 지정할 수 있는 형태의 함수를 지원합니다.
    * fun check(value: Boolean)
    인자로 받은 값이 아니라면 IllegalStateException을 발생시킵니다.
    * fun check(value: Boolean, lazyMessage: () -> Any)
    인자로 받은 value 값이 참이 아니라면 IlleagalStateException을 발생시키며, 이때 lazyMessage로 넘겨진 함수를 함께 실행합니다.
    * fun require(value: Boolean)
    인자로 받은 value 값이 참이 아니라면 IllegalArumentException을 발생 시킵니다.
    * fun require(value: Boolean, lazyMessage: () -> Any)
    인자로 받은 value 값이 참이 아니라면 IllegalArgumentException을 발생시키며, 이때 lazyMessage로 넘겨진 함수를 함께 실행합니다.
    ~~~kotlin
    fun showMessage(isPrepared: Boolean, message: String) {
        // 인자로 받은 isPrepared 값이 true가 아니라면 IllegalStateException을 발생시킵니다.
        check(isPrepared)
        // 인자로 받은 message 문자열의 길이가 10 이상이 아니라면
        // IllegalArgumentException을 발생시킵니다.
        require(message.length > 10)

        println(message)
    }
    ~~~
* 이 외에도, checkNotNull() 함수와 requireNotNull() 함수를 사용하면 특정 값의 널 여부를 확인하고 널이 아닌 값을 반환받을 수 있습니다.
* 단순히 값을 확인만 하는 형태와, 함께 실행할 함수를 지정하는 형태를 지원합니다.
    * fun <T : Any> checkNotNull(value: T?) : T
    인자로 받은 value 값이 널 값이라면 IllegalStateException을 발생시키며, 그렇지 ㅇ낳은 경우 널이 아닌 값을 반환합니다.
    * fun <T : Any> checkNotNull(vlaue: T?, lazyMessage: () -> Any) : T 
    인자로 받은 value 값이 널 값이라면 IllegalStateException을 발생시키고 lazyMessage로 넘겨진 함수를 함께 실행시키며, 그렇지 않은 경우 널이 아닌 값을 반환합니다.
    * fun <T : Any> requireNotNull(value: T?) : T
    인자로 받은 value 값이 널 값이라면 IllegalArgumentException을 발생시키며, 그렇지 않은 경우 널이 아닌 값을 반환합니다.
    * fun <T : Any> requireNotNull(value: T?, lazyMessage: () -> Any) : T
    인자로 받은 value 값이 널 값이라면 IllegalArgumentException을 발생시키고 lazyMessage로 넘겨진 함수를 함께 실행시키며, 그렇지 않은 경우 널이 아닌 값을 반환합니다.
* 다음 코드는 requireNotNull() 함수를 추가로 사용하였습니다.
~~~kotlin
fun showMessage(isPrepared: Boolean, message: String?) {
    check(isPrepared)

    // 값 msg에는 인자로 받은 message 값이 널 값이 아닐 때에만 해당 값이 할당됩니다.
    val msg = requireNotNull(message)
    require(msg.length > 10)

    println(message)
}
~~~
## 명시적으로 실행 중단하기: erroe, TODO
* 프로그램의 로직을 작성하다 보면, 정상적으로 프로그램이 실행될 경우 호출될 가능성이 없는 영역이 있습니다. 그런데 알 수 없는 이유로 실행 시점에서 이 영역에 진입하게 될 경우, 그로 인한 부작용을 예측하기 어려워집니다.
* 이 영역이 진입하게 되는 경우 임의로 예외를 발생시켜 프로그램의 실행을 막는 방법을 주로 사용합니다.
* 임의로 예외를 발생시킬 때, 코틀린에서는 error() 함수를 사용하여 리를 간편하게 구현할 수 있습니다.
    * fun error(message: String) : Nothing
    인자로 받은 message와 함께 IllegalStateException을 발생시킵니다.
    * 간단한 예
    ~~~kotlin
    fun showMessage(isPrepared: Boolean, message: String) {
        // 인자로 받은 값 isPrepared가 거짓일 경우
        // IllegalStateException: Not prepared yet 예외가 발생합니다.
        if(!isPreprared) {
            error("Not prepared yet")
        }
        println(message)
    }
    ~~~
* 이 외에도, 큰 규모의 개발을 진행하다 보면 다른 부분의 작업이 완료되어야 구현이 가능한 부분이 생기기도 합니다. 이때, 보통 주석을 사용하여 추가 작업이 필요함을 표시하고 값 반환이 필요한 경우 임의의 값을 반환하도록 구현해 두는 경우가 많습니다.
* 하지만 간혹 이러한 주석들을 미처 확인하지 못하고 그냥 두어 버그가 발생하기도 합니다. 이러한 문제를 방지하기 위해 코틀린에서는 TODO() 함수를 제공합니다.
    * fun TODO(): Nothing
    NotImplementedError 예외를 발생시켜 이 부분이 아직 완성되지 않았음을 알려줍니다.
    * fun TODO(reason: String): Nothing
    NotImplementedError 'fun TODO(): Nothing'과 똑같이 작동하지만 에러 메시지에 표시될 상세 내용을 reason 매개변수를 통해 전달할 수 있습니다.
    ~~~kotlin
    class Car {
        // 내부 구현이 완료된 함수
        fun drive() {
            ...
        }

        // 내부 구현이 아직 완료되지 않은 함수
        // 이 함수를 호출할 경우 NotImplementedError가 발생합니다.
        fun stop() {
            TODO("Brake is not implemented")
        }
    }
    ~~~